/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package eadcw;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.sql.*;

/**
 *
 * @author LENOVO
 */
public class ballot extends javax.swing.JInternalFrame {
    public int voterid;
    public String id;
    /**
     * Creates new form ballot
     */
    public ballot() {
        
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
       try {
    String url = "jdbc:mysql://localhost/votingsystem";
    String username = "root";
    String password = "";

    try (Connection conn = DriverManager.getConnection(url, username, password)) {
        String sql = "SELECT * FROM candidate_info";

        try (PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {
                Vector<String> row = new Vector<>();
                row.add(rs.getString("candidatename"));
                row.add(rs.getString("partyname"));
                dtm.addRow(row);
            }
        }
    }
} catch (SQLException e) {
    e.printStackTrace();
}
       
       
try {
        String url = "jdbc:mysql://localhost/votingsystem";
        String username = "root";
        String password = "";

        try (Connection conn = DriverManager.getConnection(url, username, password)) {
            String sql = "SELECT candidatename FROM candidate_info";
            try (PreparedStatement stmt = conn.prepareStatement(sql);
                 ResultSet rs = stmt.executeQuery()) {
                // Clear existing items in the combobox
                cmbcandidate.removeAllItems();
                cmbcandidate.addItem("Select a candidate");
                while (rs.next()) {
                    String candidate = rs.getString("candidatename");
                    cmbcandidate.addItem(candidate);
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbcandidate = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbagree = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\icons8-vote-64 (1).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 73, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Candidate Name", "Party Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Candidate Name");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Party Name");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 130));
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 240, 30));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\icons8-search-24.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Search by Party Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 160, -1));

        cmbcandidate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "     -- select a candidate --" }));
        cmbcandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcandidateActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcandidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Vote");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        cbagree.setText("By checking this box, I confirm that I cast the vote and will  be responsible for carrying out the vote.");
        cbagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbagreeActionPerformed(evt);
            }
        });
        getContentPane().add(cbagree, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 550, 20));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 80, -1));
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 180, 30));

        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void setval(String value)
    {
     this.id=value;
//     JOptionPane.showMessageDialog(rootPane, id);
        System.out.println(id);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String searchValue = txtsearch.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    try {
        String url = "jdbc:mysql://localhost/votingsystem";
        String username = "root";
        String password = "";

        try (Connection conn = DriverManager.getConnection(url, username, password)) {
            String sql = "SELECT * FROM candidate_info WHERE partyname LIKE ?";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, "%" + searchValue + "%");
                try (ResultSet rs = stmt.executeQuery()) {
                    while (rs.next()) {
                        String candidate = rs.getString("candidatename");
                        String party = rs.getString("partyname");
                        Object[] rowData = { candidate, party };
                        model.addRow(rowData);
                    }
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbagreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbagreeActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:

        
                    //

                    

    }//GEN-LAST:event_jTable1AncestorAdded

    private void cmbcandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcandidateActionPerformed
        // TODO add your handling code here:
         
        
    }//GEN-LAST:event_cmbcandidateActionPerformed
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
            if(cmbcandidate.getSelectedIndex()!=0 && cbagree.isSelected()==true && txtusername.getText()!=null){
                
                try{
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/votingsystem", "root", "" );
        String sql = "INSERT INTO vote values(?, ?)";
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setString(1, txtusername.getText());
        
        statement.setString(2, (String) cmbcandidate.getSelectedItem());
        int rowsUpdated = statement.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(rootPane, "Your vote has been Submited to \n candidate : " +cmbcandidate.getSelectedItem());
            System.out.println("Insert successfully.");
        }

        statement.close();
        connection.close();
        } 
        catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "You have use your vote");
        }
                
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"Please check if you \n Select a canditade \n check the agree status \n enterd your username");
            }
        

    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox cbagree;
    private javax.swing.JComboBox<String> cmbcandidate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtsearch;
    public javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

    private void print(SQLException e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setval() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private static class DefualtTableModel {

        public DefualtTableModel() {
        }

        private void addRow(String[] tbdata) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
