/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package eadcw;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTextField;
/**
 *
 * @author LENOVO
 */

public class userprofile extends javax.swing.JInternalFrame {
//    public int nic;
     int nic;
    
    int result = 0 ;
    public userprofile( ) {
        
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        txtfullname.setEditable(false);
        txtnic.setEditable(false);
        txtaddress.setEditable(false);
        txtmail.setEditable(false);
        txtphone.setEditable(false);
        btnsave.setVisible(false);
     
        
        display(20011);
    }
    
    public void display(int a){
        nic = a;
        String url = "jdbc:mysql://localhost/votingsystem";
        String username = "root";
        String password = "";
        try (Connection conn = DriverManager.getConnection(url, username, password)) {
         String sql = "SELECT * FROM voter_info WHERE NIC = ?";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                // Execute the query
                 stmt.setInt(1,nic );
                try (ResultSet rs = stmt.executeQuery()) {
                    if (rs.next()) {
                        // Retrieve the value from the result set
                        String fullname = rs.getString("fullname");
                        String email = rs.getString("email");
                        String address = rs.getString("address");
                        int NaIC = rs.getInt("NIC");
                        String NICs = Integer.toString(NaIC);
                        int phone = rs.getInt("phone");
                        String phones = Integer.toString(phone);
                         
                        // Set the value in the text field
                        txtfullname.setText(fullname);
                        txtmail.setText(email);
                        txtaddress.setText(address);  
                        txtnic.setText(NICs);
                        txtphone.setText(phones);
                        
                        
                        
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtfullname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnpassword = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();

        setName(""); // NOI18N
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Full Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txtfullname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtfullnameMousePressed(evt);
            }
        });
        txtfullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfullnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 633, -1));

        jLabel2.setText("National Identity Card No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txtnic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnicMousePressed(evt);
            }
        });
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });
        getContentPane().add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 280, -1));

        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        txtaddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtaddressMousePressed(evt);
            }
        });
        getContentPane().add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 430, -1));

        jLabel4.setText("Email Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        txtmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtmailMousePressed(evt);
            }
        });
        getContentPane().add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 240, -1));

        jLabel5.setText("Phone No.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        txtphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtphoneMousePressed(evt);
            }
        });
        getContentPane().add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 240, -1));

        btnsave.setText("Save Details");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 120, -1));

        btnpassword.setText("Change Password");
        btnpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        btnedit.setText("Edit Details");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 120, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\icons8-user-64 (1).png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 80));

        btndelete.setText("Delete Account");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void viewdata(){
        
    }
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        result=0;
        btnedit.setVisible(true);
        btnpassword.setVisible(true);
        txtfullname.setEditable(false);
        txtnic.setEditable(false);
        txtaddress.setEditable(false);
        txtmail.setEditable(false);
        txtphone.setEditable(false);
        btnsave.setVisible(false);
        btndelete.setVisible(true);
        
        
        
        try{
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/votingsystem", "root", "" );
        String sql = "UPDATE voter_info SET fullname = ?, address = ?, email = ?, phone = ? WHERE NIC = ?";
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setString(1, txtfullname.getText());
        statement.setString(2, txtaddress.getText());
        statement.setString(3, txtmail.getText());
        statement.setInt(4, Integer.parseInt(txtphone.getText()));
        statement.setInt(5, nic);
         int rowsAffected = statement.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Profile updated successfully.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        catch(Exception exception){
            JOptionPane.showMessageDialog(null, "Data Cannot be updated becuase of :"+exception);
            display(nic);
        }
    
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtfullnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfullnameMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtfullnameMousePressed

    private void txtnicMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnicMousePressed
        // TODO add your handling code here:
        if (result==1) {
            JOptionPane.showMessageDialog(null, "NIC cannot be change");
        }
        
        
    }//GEN-LAST:event_txtnicMousePressed

    private void txtaddressMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtaddressMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtaddressMousePressed

    private void txtmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmailMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtmailMousePressed

    private void txtphoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtphoneMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtphoneMousePressed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        result=1;
        txtfullname.setEditable(true);
        txtnic.setEditable(false);
        txtaddress.setEditable(true);
        txtmail.setEditable(true);
        txtphone.setEditable(true);
        btnpassword.setVisible(false);
        btnedit.setVisible(false);
        btnsave.setVisible(true);
        btndelete.setVisible(false);
        
    }//GEN-LAST:event_btneditActionPerformed

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void btnpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpasswordActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        changepassword cp = new changepassword();
        cp.setVisible(true);
        
    }//GEN-LAST:event_btnpasswordActionPerformed

    private void txtfullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfullnameActionPerformed
        
        
    }//GEN-LAST:event_txtfullnameActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formAncestorAdded

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost/votingsystem";
        String username = "root";
        String password = "";

        // SQL query to delete voter details
        String sql = "DELETE FROM voter_info WHERE NIC = ?";

        // Voter ID of the record to be deleted
        int voterIdToDelete = nic; // Replace with the actual voter ID you want to delete

        try (Connection conn = DriverManager.getConnection(url, username, password);
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            // Set the voter ID parameter
            stmt.setInt(1, voterIdToDelete);

            // Execute the delete query
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(rootPane, "Voter account deleted successfully.");
                String p = null ;
                userdashbord u = new userdashbord(p);
                u.dispose();
                login l = new login();
                l.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "No matching voter details found.");
                
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btndeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnpassword;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtaddress;
    public javax.swing.JTextField txtfullname;
    private javax.swing.JTextField txtmail;
    public javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
